# <font color = "BLUE" > <b><i>Pima Indians Diabetics Using ANN</b>
<b><i>NAKKA SHEKHAR</b>
* [linkedin](https://www.linkedin.com/in/nakka-shekhar-2019a987/)
* [github](https://github.com/shekhar443/MACHINE-LEARNING-PROJECT)
    
<b>Steps Followed:</b>
* Importing Required Libraries
* Data Profiling / Data Loading
* Summarize Dataset
* Segregate Data into X and y(Independent and Independent Features)
* Splitting data into Train and Test
* Feature Scaling
* Model Building and Training
* Model evaluation

### Importing Required Libraries

In [1]:
from numpy import loadtxt
import tensorflow
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import ReLU,ELU,PReLU,LeakyReLU
from tensorflow.keras.layers import Dropout

### Data Profiling / Data Loading

In [3]:
dataset=pd.read_csv("ML/pima-indians-diabetes28.csv", delimiter=',')

### Summarize Dataset

In [4]:
dataset.head()

6  148  72  35    0  33.6  0.627  50  1
0  1   85  66  29    0  26.6  0.351  31  0
1  8  183  64   0    0  23.3  0.672  32  1
2  1   89  66  23   94  28.1  0.167  21  0
3  0  137  40  35  168  43.1  2.288  33  1
4  5  116  74   0    0  25.6  0.201  30  0

### Segregate Data into X and y(Independent and Independent Features)

In [5]:
X=dataset.iloc[:,:8]
y=dataset.iloc[:,8]

In [6]:
X

6  148  72  35    0  33.6  0.627  50
0     1   85  66  29    0  26.6  0.351  31
1     8  183  64   0    0  23.3  0.672  32
2     1   89  66  23   94  28.1  0.167  21
3     0  137  40  35  168  43.1  2.288  33
4     5  116  74   0    0  25.6  0.201  30
..   ..  ...  ..  ..  ...   ...    ...  ..
762  10  101  76  48  180  32.9  0.171  63
763   2  122  70  27    0  36.8  0.340  27
764   5  121  72  23  112  26.2  0.245  30
765   1  126  60   0    0  30.1  0.349  47
766   1   93  70  31    0  30.4  0.315  23

[767 rows x 8 columns]

In [7]:
y

0      0
1      1
2      0
3      1
4      0
      ..
762    0
763    0
764    0
765    1
766    0
Name: 1, Length: 767, dtype: int64

### Splitting data into Train and Test

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

### Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [10]:
X_train

array([[ 2.38812034e+00, -1.01923779e+00,  2.23096671e-01, ...,
         4.05338503e-01, -2.70450954e-01,  1.21161571e+00],
       [-8.40103885e-01, -1.30733892e+00,  2.78749854e-01, ...,
         1.55342874e-03, -2.16193009e-01, -9.67339522e-01],
       [-8.40103885e-01, -9.55215312e-01, -4.44741520e-01, ...,
        -5.85770315e-01,  3.38443760e-01, -7.99727582e-01],
       ...,
       [-5.46628955e-01, -3.79013046e-01, -4.44741520e-01, ...,
        -8.30488542e-01, -1.02403352e+00, -1.05114549e+00],
       [ 2.38812034e+00,  6.45346538e-01,  8.35281680e-01, ...,
         6.62292640e-01, -6.74371209e-01,  6.24973915e-01],
       [-8.40103885e-01, -1.24331645e+00,  1.11790306e-01, ...,
        -6.59185783e-01, -5.56812328e-01, -7.99727582e-01]])

In [11]:
X_test

array([[ 0.62727076, -0.69912542, -0.66735425, ...,  0.24627166,
        -0.11370578,  0.79258586],
       [-0.84010388,  1.18953757,  0.11179031, ..., -0.7815449 ,
        -1.03910517, -0.79972758],
       [-0.54662896, -0.37901305, -0.33343516, ..., -0.14527751,
        -0.93360361, -1.05114549],
       ...,
       [-0.54662896, -1.17929397, -0.22212879, ...,  0.02602525,
         0.08825435, -0.96733952],
       [ 1.80117048, -0.15493439, -3.89523884, ...,  0.4053385 ,
        -1.00594754, -0.38069773],
       [ 0.62727076,  0.10115551,  0.11179031, ...,  0.19732801,
         0.79963629,  0.03833212]])

### Model Building and Training

In [12]:
model = Sequential([
  Dense(12, activation='relu',input_shape=(8,)),
  Dense(8, activation='relu'),
  Dense(1, activation='sigmoid')])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 12)                108       
                                                                 
 dense_1 (Dense)             (None, 8)                 104       
                                                                 
 dense_2 (Dense)             (None, 1)                 9         
                                                                 
Total params: 221
Trainable params: 221
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.compile(loss="binary_crossentropy",optimizer="adam",metrics="accuracy")
model.fit(X,y,epochs=100,batch_size=10)

Epoch 1/100
77/77 [==============================] - 2s 3ms/step - loss: 7.9520 - accuracy: 0.4316
Epoch 2/100
77/77 [==============================] - 0s 3ms/step - loss: 2.1579 - accuracy: 0.5059
Epoch 3/100
77/77 [==============================] - 0s 3ms/step - loss: 1.4434 - accuracy: 0.5241
Epoch 4/100
77/77 [==============================] - 1s 8ms/step - loss: 1.1128 - accuracy: 0.5411
Epoch 5/100
77/77 [==============================] - 0s 3ms/step - loss: 0.9201 - accuracy: 0.5346
Epoch 6/100
77/77 [==============================] - 0s 3ms/step - loss: 0.8046 - accuracy: 0.5580
Epoch 7/100
77/77 [==============================] - 0s 3ms/step - loss: 0.7458 - accuracy: 0.5828
Epoch 8/100
77/77 [==============================] - 0s 3ms/step - loss: 0.7013 - accuracy: 0.5997
Epoch 9/100
77/77 [==============================] - 0s 3ms/step - loss: 0.6834 - accuracy: 0.6558
Epoch 10/100
77/77 [==============================] - 0s 3ms/step - loss: 0.6757 - accuracy: 0.6284
Epoch 11/

In [14]:
eval_model_for_trainingData=model.evaluate(X_train, y_train)
eval_model_for_trainingData

18/18 [==============================] - 0s 4ms/step - loss: 0.7436 - accuracy: 0.6539


[0.7436472773551941, 0.6539130210876465]

In [15]:
eval_model_for_testData=model.evaluate(X_test, y_test)
eval_model_for_testData

6/6 [==============================] - 0s 8ms/step - loss: 0.7122 - accuracy: 0.6458


[0.7122265696525574, 0.6458333134651184]

In [16]:
y_pred=model.predict(X_test)
y_pred =(y_pred>0.5)

6/6 [==============================] - 0s 4ms/step


### Model evaluation

In [17]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[124   0]
 [ 68   0]]
